name: build

on:
  push:
    paths:
        - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
    
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
        
      - name: Build the project
        run: cargo build --release

      - name: Run tests
        run: cargo test
      